
// ── Shopify CSV ───────────────────────────────────────────────────────────────
// export const SHOPIFY_HEADERS = [
//   'Handle','Title','Body (HTML)','Vendor','Product Category','Type','Tags','Published',
//   'Option1 Name','Option1 Value','Variant SKU','Variant Grams','Variant Inventory Tracker',
//   'Variant Inventory Qty','Variant Inventory Policy','Variant Fulfillment Service',
//   'Variant Price','Variant Compare At Price','Variant Requires Shipping','Variant Taxable',
//   'Status',
// ];

export const SHOPIFY_HEADERS =  [
  "Handle",
  "Command",
  "Title",
  "Body HTML",
  "Vendor",
  "Type",
  "Tags",
  "Tags Command",
  "Status",
  "Published",
  "Published At",
  "Published Scope",
  "Template Suffix",
  "Gift Card",
  "Category: ID",
  "Category: Name",
  "Category",
  "Custom Collections",
  "Image Attachment",
  "Image Src",
  "Image Command",
  "Image Position",
  "Title 1",
  "Variant ID",
  "Variant Command",
  "Option1 Name",
  "Option1 Value",
  "Option2 Name",
  "Option2 Value",
  "Option3 Name",
  "Option3 Value",
  "Variant Generate From Options",
  "Variant Position",
  "Variant SKU",
  "Variant Weight",
  "Variant Weight Unit",
  "Variant HS Code",
  "Variant Country of Origin",
  "Variant Province of Origin",
  "Variant Price",
  "Variant Compare At Price",
  "Variant Cost",
  "Variant Requires Shipping",
  "Variant Taxable",
  "Variant Tax Code",
  "Variant Barcode",
  "Variant Image",
  "Variant Inventory Tracker",
  "Variant Inventory Policy",
  "Variant Fulfillment Service",
  "Variant Inventory Qty",
  "Variant Inventory Adjust",
  "Metafield:custom.fabric [string]",
  "Metafield:custom.pattern [string]",
  "Metafield:custom.fit [string]",
  "Metafield:custom.sleeve [string]",
  "Metafield:custom.lining [string]",
  "Metafield:custom.wash_care [string]",
  "Metafield:custom.transparency [string]",
  "Metafield:custom.closure [string]"
];