/**
 * Nykaa Fashion constants
 */
import { MYNTRA_SIZE_RANGES, MYNTRA_SIZE_MAPPING } from '../../myntra/Constants/index.js';

export const NYKAA_SIZE_RANGES = MYNTRA_SIZE_RANGES;
export const NYKAA_SIZE_MAPPING = MYNTRA_SIZE_MAPPING;

export const NYKAA_BRAND_DEFAULTS = {
  brand: 'Brand_Name',
  countryOfOrigin: 'India',
};

export const NYAKAA_GLOBAL_HEADERS = [
  'Vendor SKU Code',
  'Gender',
  'Brand Name',
  'Style Code',
  'Product Name',
  'Description',
  'Price',
  'Color',
  'Country of Origin',
  'Manufacturer Name',
  'Manufacturer Address',
  'Ean Codes',
  'brand  size',
  'Design Code',
  'Multipack Set',
  'Occasion',
  'Season',
  'Care Instruction',
  'HSN Codes',
  'Ships In Days',
  'Pack Contains',
  'Net Qty',
  'Material',
  'Responsibility Criteria',
  'Pocket Description',
  'Pattern',
  'Disclaimer',
  'Dress Shape',
  'Collections Function',
  'Closure',
  'Dresses Type',
  'Character/Collection Shop',
  'Neckline',
  'Sleeve length Type',
  'Style Bucket',
  'Model details',
  'Fit',
  'Age',
  'Bust for Garment (Inches)',
  'Chest for Garment (Inches)',
  'Waist for Garment (Inches)',
  'Hip for Garment (Inches)',
  'Shoulder for Garment (Inches)',
  'Sleeve Length (Inches)',
  'Bust For Body (Inches)',
  'Chest For Body (Inches)',
  'Waist For Body (Inches)',
  'Hip For Body (Inches)',
  'Shoulder For Body (Inches)',
  'Length For Body (Inches)',
  'Category Classification',
  'Type of Work',
  'Topwear Length',
  'Length (Inches)',
  'Age Group',
  'Activity',
  'Shirts Tops and Crop Tops Subcategory',
  'Rise Style',
  'Bottoms Pants and Trousers Subcategory',
  'Bottom Length for Garment (Inches)',
  'Inseam for Garment (Inches)',
  'Inseam For Body (Inches)',
  'Bottom Length For Body (Inches)',
  'Skirts Subcategory',
  'Front Styling',
  'Jackets and Coats Subcategory',
  'Leg Style',
  'Front Image',
  'Back Image',
  'Additional Image 1',
  'Additional Image 2',
  'Additional Image 3',
  'Additional Image 4',
  'Additional Image 5',
  'Additional Image 6',
  'Additional Image 7',
  'Additional Image 8',
];
