 export const MARKETPLACES = [
  {
    id: 'shopify',
    name: 'Shopify',
    tagline: 'All-in-one commerce platform',
    accentColor: '#96BF48',
    bgGrad: 'from-[#f0fce8] to-[#e4f7d0]',
    border: '#96BF48',
    singleFile: true,
    status: 'ready',
    description: 'Single CSV · All categories',
  },
//   {
//     id: 'myntra',
//     name: 'Myntra',
//     tagline: 'India\'s leading fashion platform',
//     accentColor: '#FF3F6C',
//     bgGrad: 'from-[#fff0f4] to-[#ffe0e8]',
//     border: '#FF3F6C',
//     singleFile: false,
//     status: 'soon',
//     categories: [
//       'Women Dresses','Women Tops','Women Kurtas','Women Skirts','Women Palazzos',
//       'Women Sarees','Women Lehenga','Women Jackets & Coats','Men Shirts',
//       'Men T-Shirts','Men Trousers','Men Kurtas','Men Jackets','Kids Clothing',
//       'Sports & Active','Ethnic Wear','Winter Wear','Accessories',
//     ],
//   },
//   {
//     id: 'amazon',
//     name: 'Amazon',
//     tagline: 'World\'s largest marketplace',
//     accentColor: '#FF9900',
//     bgGrad: 'from-[#fff8ee] to-[#ffefd4]',
//     border: '#FF9900',
//     singleFile: false,
//     status: 'soon',
//     categories: [
//       'Women Clothing','Men Clothing','Girls Clothing','Boys Clothing','Sarees',
//       'Kurtas & Kurtis','Lehenga Choli','Salwar Suits','Ethnic Sets',
//       'Western Dresses','Tops & Tees','Jeans & Trousers','Jackets & Coats',
//       'Activewear','Accessories',
//     ],
//   },
//   {
//     id: 'flipkart',
//     name: 'Flipkart',
//     tagline: 'India\'s e-commerce giant',
//     accentColor: '#2874F0',
//     bgGrad: 'from-[#eef4ff] to-[#dceaff]',
//     border: '#2874F0',
//     singleFile: false,
//     status: 'soon',
//     categories: [
//       'Women Ethnic','Women Western','Men Ethnic','Men Western','Kids Wear',
//       'Sarees','Kurtas','Lehengas','Dresses','Tops','T-Shirts','Shirts',
//       'Trousers','Jackets','Sportswear',
//     ],
//   },
//   {
//     id: 'nykaa',
//     name: 'Nykaa Fashion',
//     tagline: 'Premium fashion & beauty',
//     accentColor: '#FC2779',
//     bgGrad: 'from-[#fff0f6] to-[#ffe0ee]',
//     border: '#FC2779',
//     singleFile: false,
//     status: 'soon',
//     categories: [
//       'Dresses','Tops & Tunics','Kurtas','Skirts','Palazzos','Sarees',
//       'Lehenga','Jackets','Coats','Jumpsuits','Co-ord Sets','Loungewear',
//       'Activewear','Ethnic Sets',
//     ],
//   },
//   {
//     id: 'ajio',
//     name: 'Ajio',
//     tagline: 'Reliance fashion destination',
//     accentColor: '#8B2FC9',
//     bgGrad: 'from-[#f7f0ff] to-[#ecdeff]',
//     border: '#8B2FC9',
//     singleFile: false,
//     status: 'soon',
//     categories: [
//       'Women Dresses','Women Tops','Women Kurtas','Women Ethnic','Women Western',
//       'Men Shirts','Men T-Shirts','Men Ethnic','Men Casual','Kids Clothing',
//       'Fusion Wear','Activewear','Winter Wear','Accessories',
//     ],
//   },
//   {
//     id: 'tatacliq',
//     name: 'Tata CLiQ',
//     tagline: 'Premium & luxury fashion',
//     accentColor: '#DC143C',
//     bgGrad: 'from-[#fff0f2] to-[#ffdde2]',
//     border: '#DC143C',
//     singleFile: true,
//     status: 'soon',
//     description: 'Single CSV · All categories',
//   },
//   {
//     id: 'snapdeal',
//     name: 'Snapdeal',
//     tagline: 'Value fashion for everyone',
//     accentColor: '#E40046',
//     bgGrad: 'from-[#fff0f3] to-[#ffd6df]',
//     border: '#E40046',
//     singleFile: false,
//     status: 'soon',
//     categories: [
//       'Women Ethnic','Women Western','Men Clothing','Kids Wear','Sarees',
//       'Kurtas','Lehengas','Dresses','Tops','Shirts','T-Shirts','Trousers','Jackets',
//     ],
//   },
//   {
//     id: 'shoppersstop',
//     name: "Shoppers Stop",
//     tagline: 'Omnichannel retail leader',
//     accentColor: '#1A1A2E',
//     bgGrad: 'from-[#f2f2f7] to-[#e4e4ef]',
//     border: '#1A1A2E',
//     singleFile: true,
//     status: 'soon',
//     description: 'Single CSV · All categories',
//   },
];