export const CHANNELS = [
  {
    id: 'myntra',
    name: 'Myntra',
    accentColor: '#FF3F6C',
    categories: ['Women Dresses', 'Women Tops', 'Women Shirt', 'Women Skirts'],
  },
  {
    id: 'nykaa',
    name: 'Nykaa Fashion',
    accentColor: '#FC2779',
    categories: [
      'Dresses',
      'Tops & Tunics',
      'Kurtas',
      'Skirts',
      'Palazzos',
      'Sarees',
      'Lehenga',
      'Jackets',
      'Coats',
      'Jumpsuits',
      'Co-ord Sets',
      'Loungewear',
      'Activewear',
    ],
  },
  {
    id: 'ajio',
    name: 'Ajio',
    accentColor: '#8B2FC9',
    categories: [
      'Women Dresses',
      'Women Tops',
      'Women Kurtas',
      'Women Ethnic',
      'Women Western',
      'Men Shirts',
      'Men T-Shirts',
      'Men Ethnic',
      'Men Casual',
    ],
  },
  {
    id: 'tatacliq',
    name: 'Tata CLiQ',
    accentColor: '#DC143C',
    categories: ['All Categories'],
  },
  {
    id: 'amazon',
    name: 'Amazon',
    accentColor: '#FF9900',
    categories: [
      'Women Clothing',
      'Men Clothing',
      'Girls Clothing',
      'Boys Clothing',
      'Sarees',
      'Kurtas & Kurtis',
      'Western Dresses',
      'Tops & Tees',
    ],
  },
  {
    id: 'flipkart',
    name: 'Flipkart',
    accentColor: '#2874F0',
    categories: [
      'Women Ethnic',
      'Women Western',
      'Men Ethnic',
      'Men Western',
      'Sarees',
      'Kurtas',
      'Dresses',
      'Tops',
      'Shirts',
      'Trousers',
    ],
  },
  {
    id: 'shopify',
    name: 'Shopify',
    accentColor: '#96BF48',
    categories: ['All Categories'],
  },
];
